import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname, basename, sep } from "node:path";
import matter from "gray-matter";

export const INDEX_FILE = "INDEX.md";
export const INDEX_OVERFLOW_THRESHOLD = 100; // entries before we warn about splitting

export interface IndexEntry {
  path: string; // relative to the directory
  title: string;
  summary?: string;
}

export interface RegenResult {
  directory: string;
  indexPath: string;
  entryCount: number;
  overflowed: boolean;
  wrote: boolean;
}

/**
 * Regenerate INDEX.md for a single vault directory.
 * Lists every *.md file in the directory (non-recursive, excluding the index itself)
 * with its title (frontmatter or first heading) and optional summary (from frontmatter
 * `purpose` or first non-heading paragraph).
 */
export async function regenDirectoryIndex(vaultPath: string, dirRel: string): Promise<RegenResult> {
  const absDir = join(vaultPath, dirRel);
  const indexPath = join(absDir, INDEX_FILE);
  const relIndex = join(dirRel, INDEX_FILE);

  if (!existsSync(absDir)) {
    return { directory: dirRel, indexPath: relIndex, entryCount: 0, overflowed: false, wrote: false };
  }

  const files = (await readdir(absDir)).filter(
    (f) => f.endsWith(".md") && f !== INDEX_FILE && f !== "README.md"
  );

  const entries: IndexEntry[] = [];
  for (const f of files) {
    const full = join(absDir, f);
    try {
      const st = await stat(full);
      if (!st.isFile()) continue;
      const raw = await readFile(full, "utf-8");
      const { data, content } = matter(raw);
      const title = typeof data.title === "string" ? data.title : firstHeading(content) ?? basenameNoExt(f);
      const summary = typeof data.purpose === "string" ? data.purpose : firstParagraph(content);
      entries.push({ path: f, title, summary });
    } catch {
      /* skip unreadable */
    }
  }

  entries.sort((a, b) => a.title.localeCompare(b.title));
  const body = renderIndex(dirRel, entries);
  const overflowed = entries.length > INDEX_OVERFLOW_THRESHOLD;

  let wrote = false;
  if (existsSync(indexPath)) {
    const current = await readFile(indexPath, "utf-8");
    if (current !== body) {
      await writeFile(indexPath, body, "utf-8");
      wrote = true;
    }
  } else {
    await writeFile(indexPath, body, "utf-8");
    wrote = true;
  }

  return { directory: dirRel, indexPath: relIndex, entryCount: entries.length, overflowed, wrote };
}

/**
 * Regenerate indexes for every directory affected by a set of paths.
 * Walks up the parent chain for each input so a deep change at
 * `a/b/c/note.md` regenerates `a/b/c/INDEX.md`. Does NOT recurse further —
 * `a/b/INDEX.md` stays as-is unless a path under `a/b/` (not `a/b/c/`)
 * also changed.
 */
export async function regenIndexesForPaths(
  vaultPath: string,
  paths: string[]
): Promise<RegenResult[]> {
  const dirs = new Set<string>();
  for (const p of paths) {
    const d = dirname(p);
    if (d === "." || d === "/") continue;
    dirs.add(d);
  }
  const results: RegenResult[] = [];
  for (const d of dirs) {
    results.push(await regenDirectoryIndex(vaultPath, d));
  }
  return results;
}

function renderIndex(dirRel: string, entries: IndexEntry[]): string {
  const header = `# ${toTitle(dirRel)} Index\n\n> Auto-generated by semantic-sidekick. Changes are overwritten on apply_patch. Add prose to per-note files, not here.\n\n`;
  if (entries.length === 0) return header + "_No notes in this directory yet._\n";
  const overflowNote =
    entries.length > INDEX_OVERFLOW_THRESHOLD
      ? `> ⚠️  ${entries.length} entries — consider splitting this directory into subfolders (threshold: ${INDEX_OVERFLOW_THRESHOLD}).\n\n`
      : "";
  const lines = entries.map((e) => {
    const linkText = e.title;
    const target = e.path.replace(/\.md$/, "");
    const summary = e.summary ? ` — ${truncate(e.summary, 140)}` : "";
    return `- [${linkText}](./${e.path}) — \`[[${target}]]\`${summary}`;
  });
  return header + overflowNote + lines.join("\n") + "\n";
}

function toTitle(dirRel: string): string {
  return dirRel
    .split(sep)
    .pop()!
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function basenameNoExt(p: string): string {
  return basename(p).replace(/\.md$/, "");
}

function firstHeading(content: string): string | null {
  const m = content.match(/^\s*#{1,6}\s+(.+)$/m);
  return m ? m[1].trim() : null;
}

function firstParagraph(content: string): string | undefined {
  // Skip leading headings, then take the first line of non-heading text
  const lines = content.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("#")) continue;
    if (trimmed.startsWith(">")) continue;
    if (trimmed.startsWith("```")) continue;
    return trimmed.replace(/\s+/g, " ");
  }
  return undefined;
}

function truncate(s: string, n: number): string {
  return s.length <= n ? s : s.slice(0, n - 1).trimEnd() + "…";
}
